name: Python testing with pytest

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Install compiler
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.21.3'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build RadFiled3D Wheel
      run: |
        python -m pip install setuptools wheel build
        python -m build --wheel --no-isolation
    - name: Install built wheel
      run: |
        python -m pip install ./dist/*.whl
    - name: Test with pytest
      run: |
        python -m pip install pytest
        python -m pytest ./tests/
